FROM nginx

# Create app directory
WORKDIR /dist

COPY package*.json ./

# Instal pm2
RUN npm install pm2 -g
RUN npm ci

# Копируем Клиент в Дист
COPY ./src/Client /dist/

EXPOSE 8080
CMD [ "node", "server.js" ]