FROM node:lts-bullseye-slim

# Create app directory
WORKDIR /usr/src/app

COPY package*.json ./

# Instal pm2
RUN npm install pm2 -g
RUN npm i -g @nestjs/cli
RUN npm ci

# Копируем Клиент в Дист
COPY . /usr/src/app


EXPOSE 3000
CMD [ "pm2", "start", "main.js", "-i", "max" ]